SELECT P.PRODUCT_NAME,
	   P.QUANTITY_PER_UNIT,
	   P.UNIT_PRICE,
	   C.category_name,
	   C.DESCRIPTION
FROM PRODUCTS AS P
INNER JOIN
CATEGORIES AS C
ON P.CATEGORY_ID = C.CATEGORY_ID
ORDER BY P.PRODUCT_NAME